### ISSUE TITLE
Dear Colleague Riley

### ISSUE THREAD

**Issue by EimaMei** [ColleagueRiley/RSGL#5]
First things first - sorry that I have to make this into an issue and do this in such a public fashion, I genuinely didn't plan for this. I just wanted to block you and get over it, simple as that. I kinda thought that you would understand why I blocked you and all of this would've dusted away, but I didn't expect you to respond so... interestingly, to say the least.

Anyhow, as I said I didn't plan for this. However, you caught my attention when I read that you deleted a `rsgl-win.cpp` 22 hours ago. Upon closer look I quickly found out you tried taking my work and pass it off as yours in RSGL - no credit, no nothing. At first I assumed the best of you, that you realized it was morally pretty grim to do so and so you deleted it, considering you would be just copying my work without changing it and passing off as yours, which is especially messed up when this takes right after our argument. However it didn't take me long to find out you tried passing off ESGL as RSGL Windows, as I dug a little deeper.

I reacted with a simple 🚎 at [this](https://github.com/ColleagueRiley/RSGL/commit/4f337e6993338b1386d11fc657c9a0f92da7ffe0]) commit. You tried to play it off, saying how you meant to commit this privately. Why hide, unless you're hiding something from me? I called you out about it and I also mentioned your hypocrisy - how you got mad at me that I "took your shit behind your back" and yet, now you're taking my work behind my back - even privating the whole repository! Hypocritical, don't you think?

After some time I looked back at my GitHub and see that I got a notification! I joyfully checked it out and honestly - I kinda laughed. You not only did not respond to it, not only you deleted all of the comments but you also locked the entire thread. You can't take a little bit of criticism, eh Riley? Stay classy.

Anyways I just wanted to inform that due to your recent toxicity and just douchebag behaviour - I was left with no choice but to ban you from using ESGL at all publicly. You check the details [here](https://github.com/EimaMei/ESGL/blob/main/LICENSE]) for more information on what you can't do.

I hope you'll actually learn something from this, Riley. I never want to take harsh actions against close friends, but clearly you don't consider a close friend if that's how you act against me. Maybe you shouldn't assume you're always right and maybe you should think about why me, someone who has been a close friend of yours for almost 2 years, has blocked you, completely distanced away from you and had to ban you from using ESGL - a project that started out as a collaboration between us.

Best regards,
Eima

**Comment by ColleagueRiley** [comment]
Nope, I meant to commit it to a private repo so I could pull it back on my main pc. I'm not trying to hide anything and I do plan on creating windows support on this repo (with credits from ESGL sources/edits), I deleted all the comments after making a clarifying comment that I thought you had read. I'm sorry for any misunderstanding.

**Comment by EimaMei** [comment]
Maturity 100

**Comment by EimaMei** [comment]
For some reason I was blind and didn't see the comment above

**Comment by EimaMei** [comment]
> Nope, I meant to commit it to a private repo so I could pull it back on my main pc. I'm not trying to hide anything and I do plan on creating windows support on this repo (with credits from ESGL sources/edits), I deleted all the comments after making a clarifying comment that I thought you had read. I'm sorry for any misunderstanding.

Sure, in that context I get it. However that still doesn't excuse the fact that you've been recently acting very toxic against me. No matter what your intentions were, you made up assumptions, lies and called me and ESGL many things (I can't forget how you called RSGL "not a real" project yet you're planning to use it).

Also, no, I don't give you permission to use ESGL. As my license states, you cannot use it. And that's final. I have the full rights to ESGL and you should respect it. You can take hints if you need to, whatever, but porting is not something I'll allow you to do. I am sorry but you've deserved this after what you've said out loud.
